### ISSUE TITLE
开发模式下支持 proxyTable

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas-template#18]
涉及到两个模板

- release-basic
- release-appshell

**Comment by leson1986** [comment]
请问如何配置？

**Comment by PengXing** [comment]
我打算今天来实现，没想到你这么快，如果你急需，我给你一个 demo 参考

1. 在 lavas.config.js 中增加 proxy 配置

```javascript
proxy: {
    prefix: '/api',
    remote: 'https://xxx.com'
}
```

2. 修改 server.dev.js

引入 `express-http-proxy`

```javascript
const proxy = require('express-http-proxy');
```

代理请求，增加 `app.use(lavasCOnfig.proxy.prefix, proxy(lavasConfig.proxy.remote))`

```javascript
function startDevServer() {
    app = express();
    core.build()
        .then(() => {
            app.use(lavasConfig.proxy.prefix, proxy(lavasConfig.proxy.remote));
            app.use(core.expressMiddleware());
        }).catch(err => {
            console.log(err);
        });
}
```

通过上面这些，可以先实现一个简易的 proxy 功能，也可以等我今天实现完之后再使用

**Comment by leson1986** [comment]
谢谢，哈哈，刚好今天在调试接口，需要用上，像你说的，是没怎么开发node，所以只能求助您了。谢谢！

**Comment by PengXing** [comment]
PR

- basic 模板: https://github.com/lavas-project/lavas-template-vue/pull/19
- appshell 模板: https://github.com/lavas-project/lavas-template-vue/pull/20

求 REVIEW @xiaoiver  @huanghuiquan @leson1986 @easonyq

**Comment by PengXing** [comment]
@leson1986 
已经在最新的模板中实现，可以通过 `lavas init` 导出新模板体现新功能

如果你想在现有的模板上升级，参考下面的方法
- 复制 [server.dev.js](https://github.com/lavas-project/lavas-template-vue/blob/release-basic/server.dev.js) 文件内容替换本地的 `server.dev.js` 文件
- 运行 `npm i --save-dev http-proxy-middleware` 安装相关依赖包

然后重新启动开发测试服务器 `lavas dev` 就可以了

文档可以参考 [代理 API 请求](https://lavas.baidu.com/codelab/get-started/proxy-table)
