### ISSUE TITLE
Kickoff: 默认 SSR 还是 SPA

### ISSUE THREAD

**Issue by PengXing** [lavas-project/lavas-template#6]
很多开发者都很疑惑，打包完并不像普通的 Vue 项目那样输出的是静态文件，而是需要 Node.js 环境，原因有三点

1. 默认模式是 SSR
2. 开发者并不会完整的阅读文档
3. 文档没有在比较醒目的地方写明默认是 SSR

那么默认是 SPA 是不是会更好一些，然后清楚的写明怎么切换到 SSR？

**Comment by chenqiushi** [comment]
能否在 cli 导出项目的时候，加一个提示信息：当前是 SSR 模式，需要 SPA 可以在配置文件更改

**Comment by PengXing** [comment]
不失为一种方法，但是这种好呢，还是切换为 SPA 好呢？

说到底就是开发者到底是哪种方案用的比较多

**Comment by easonyq** [comment]
根据对开发者的简单统计，使用 SPA 模式的占比较高，因此 lavas-template 考虑将默认模式改成 SPA。

附上开发者QQ群的投票（去除我自己的一票 SPA，因为投票之后才能观察结果）
![image](https://user-images.githubusercontent.com/6800839/37264405-29d60a80-25e8-11e8-8956-caaf5dc217ed.png)
